### ISSUE TITLE
Grouping of Students - and having that as a prerequisite (Feature Request)

### ISSUE THREAD

**Issue by aluxenburg** [bytedeck/bytedeck#923] opened 2022-02-04 16:31 UTC
We sometimes want to group students based on projects or sections or something... after enrollment in our courses. It would be great to be able to create groups and use those as prerequisites.
This will later turn into a more complex request, as once we can create groups, we may wish to assign permissions based on those groups... assignment of quests to complete a collaboration project.... 
A can of worms... but the first part can be very useful.

**Comment by tylerecouture** [comment] 2022-02-04 17:17
Great idea.  

Current workaround would be to create team badges and assign them to members of teams, then you can organize prereqs and stuff based on those badges (Since you can create groups of badges, e.g Talents, Achievements, Awards, etc) you could create a Teams group of badges specifically for this.

Actually I'd never thought of doing this before!  

The future possibility of collaborative quest is very cool.

**Comment by aluxenburg** [comment] 2022-02-04 17:37
Good work-a-round... the badges... I will think on it.

**Comment by tylerecouture** [comment] 2022-04-15 17:31
Can you elaborated on what this feature would look like?  I'm not sure I see the benefit, since the more I think about it, it seems badges can fully handle this.

Create a badge group called "Teams", give it an icon.  You can even bulk assign students to the teams, groups, and it would allow for students to be parts of multiple teams if you wanted.

I think all this needs is to move Badge Type creation to the front end and to document it?

**Comment by aluxenburg** [comment] 2022-04-15 18:07
OK. Would work.
It seems "work-a-roundy" to me... to use a badge to create groups. I am thinking of professionalizing for future users. I think the less like work-a-rounds our features are, the more intentional they become for our future clients.  We need to not be explaining that you can create a team by creating a badge... perhaps it is "Teams and Badges", and one of the default options is "teams".

**Comment by tylerecouture** [comment] 2022-04-15 18:40
I originally thought of it as a work around too, but it actually seems like the elegant way to do it.  Badges are a generic organizational feature.  You can use them for awards, achievements, talents, groups, cohorts or really anything.  They are very flexible and it makes sense to me to use them in this way.  It's also more robust, because then any feature we add to badges will be available to all different badge types and badges (and less unnecessary duplication).

Here's an example, this doesn't look work aroundy to me:

![image](https://user-images.githubusercontent.com/10604391/163608556-8d6b4f8a-395a-4927-9ecb-fe401e0e6999.png)

I do agree it might make sense to add a default badge type called "Teams" or "Groups".  Or in our documentation we just explain some of the common use cases and how to implement them.

**Comment by aluxenburg** [comment] 2022-04-15 18:50
I agree.
However... I honestly think that we should ween ourselves off relying on documentation to explain things.  The best scenario is to not need to explain things. If we can make things obvious and intuitive for our new clientele, we will have fewer problems and provide obvious possibilities. If in the titling and organization of something we can also be stating what it is for, then we are making things more intuitive. Example: Calling Admin: Database Admin confuses things... calling it "Scary Admin Space" tells people what it is AND tells them to be careful.  I think you get the point.

**Comment by tylerecouture** [comment] 2022-04-15 19:17
Ya I agree with all that for sure.  The problem is you can only do that for the most simple use cases.  If we want the system to be flexible and robust, then there are going to be a lot of advanced features you can turn on and off, and that can get quite complicated, especially when they interact with each other. 

I think we'll want most of them off by default to prevent the initial feature set from becoming too overwhelming.  We will need to make some tradeoffs which features are upfront/defaults and which are not, and I don't think those will be easy to figure out because so far, everyone who uses the system uses it differently!  You probably think the way you use it makes sense and should be defaults, and I think the way I use it should be the defaults, lol. Sounds like a summer meeting to hash this out? 

I don't see how we can avoid tutorials or documentation for features beyond the most basic starter deck.  I think the minimum feature set to get up and running, those should be made absolutely dead simple and obvious to use, and then once they're set up and start thinking "OK, so how do I do this?"  Then that's where a robust, searchable documentation kicks in?

**Comment by tylerecouture** [comment] 2022-08-11 19:39
I'm going to close this, now that we've determined to re-factor the current "Grade" into "Group", so this will be solved when #919 is completed.  Since Group (previously Grade) is already a prerequisite, that part of this request will be solved as well.

In addition #1056 adds an alternate method of grouping students and setting it as a prerequisite, by using a "Team" or "Group" Badge Type and assigning them to students.

**Closed by tylerecouture** 2022-08-11 19:39 UTC
Labels: priority, feature request
