### ISSUE TITLE
Related Maps from Quest

### ISSUE THREAD

**Issue by fjbagley** [bytedeck/bytedeck#1413] opened 2023-06-26 17:40 UTC
This was a suggestion from a student that I beliveve would be a good addition:

A see quest on map button at the top of the quest. It would take the user from that quest to the quest map that it is located in.

**Comment by tylerecouture** [comment] 2023-06-26 22:14
It's a good idea. Thanks for the reminder. Duplicate of #273

**Closed by tylerecouture** 2023-06-26 22:14 UTC
Labels: duplicate
