### ISSUE TITLE
New prerequisites are not showing available items

### ISSUE THREAD

**Issue by aluxenburg** [bytedeck/bytedeck#1222] opened 2022-09-12 17:37 UTC
I have been trying to add a prerequisite to a quest in the new prerequisites section of a quest.
I wanted to add an AND NOT to groups that have a specific badge.
I typed the whole name of the badge in the space provided and it said the search could not find it.
I tried several times.
I tried it in the "alternate element" spot and it DID find the badge I was looking for.
However... that would make it an OR function and that is not going to work.
<img width="546" alt="Screenshot at Sep 12 10-36-48" src="https://user-images.githubusercontent.com/95307054/189719986-f9c195ad-6957-41fa-a9dc-c7980efc74ae.png">

**Comment by tylerecouture** [comment] 2022-09-12 17:55
A couple questions to help me troubleshoot this:

1. Does it show up if you refresh the page and try again?
2. What's the name of the badge so I can inspect the problem directly.

Thanks!

**Comment by aluxenburg** [comment] 2022-09-12 18:03
I have tried to refresh the page and it does not show up.
I have tried with a quest as well (as per screenshot) and that also did not work.
I am wondering if I should try on a different browser as well?

**Comment by aluxenburg** [comment] 2022-09-12 18:21
Just tried it on a different browser with the same result.

**Comment by aluxenburg** [comment] 2022-09-13 14:29
This is the quest I was playing with.
https://edpb530.bytedeck.com/quests/117/

**Comment by aluxenburg** [comment] 2022-09-15 12:57
Just tried it again and it worked really well.  It brought up the quest with only the first word in the title typed in. This is a huge improvement. Did you "fix" this?

**Comment by tylerecouture** [comment] 2022-09-15 13:51
Nothing changed. I'm guessing this inconsistency is related to server response time. We will definitely investigate. The lack of consistancy is frustrating.

**Comment by tylerecouture** [comment] 2022-12-03 05:09
Duplicate of #1154

**Closed by tylerecouture** 2022-12-03 05:09 UTC
Labels: duplicate
