### ISSUE TITLE
Image for Ranks (Feature Request)

### ISSUE THREAD

**Issue by aluxenburg** [bytedeck/bytedeck#924] opened 2022-02-04 16:33 UTC
Once less tech-savvy teachers begin to use ByteDeck, changing the Awesome Fonts in Ranks is going to be a challenge.
If we could use images instead, that might be better for folks. 
Or.. provide an option to see the rank text rather than the icon at the top.

**Comment by tylerecouture** [comment] 2022-02-04 17:40
Yep, that definitely needs to be more user friendly.

**Comment by tylerecouture** [comment] 2022-06-02 01:48
New option available to integrate FA with django.  Just need an Icon model field, or a font-awesome widget to go with it:
https://fontawesome.com/docs/web/use-with/python-django
https://github.com/BenjjinF/django-fontawesome-5

**Comment by tylerecouture** [comment] 2022-06-02 02:07
#492 would solve this.

**Comment by tylerecouture** [comment] 2022-08-10 21:37
Removing as duplicate of 492

**Closed by tylerecouture** 2022-08-10 21:37 UTC
Labels: enhancement
