### ISSUE TITLE
Create a Semester Causes 500 Error 

### ISSUE THREAD

**Issue by fjbagley** [bytedeck/bytedeck#1417] opened 2023-06-28 18:45 UTC
After adding excluded dates to new semester and clicking create a 500 Server error occurs.
Semester has actually been added though. Related to previous issue?

**Comment by fjbagley** [comment] 2023-06-28 18:51
Is related to #1416 as excluded dates are not appearing in Django.

**Comment by tylerecouture** [comment] 2023-06-28 19:16
Can you reproduce or provide more detailed steps or screenshots? It's working for me.  Any chance you hit back on the browser or any other context that could help find this?

**Comment by tylerecouture** [comment] 2023-06-28 19:16
Is this in the django admin or on the front website at /courses/semesters/add?

**Comment by tylerecouture** [comment] 2023-06-28 19:39
Duplicate of #1241.  Need to figure out how to reproduce this bug so we can fix it, but I can get it to happen.

**Closed by tylerecouture** 2023-06-28 19:39 UTC
